import type { Metadata } from "next";
import { Inter_Tight, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const interTight = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-sans",
});

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interTight.variable} ${jetBrainsMono.variable} antialiased`}
      >
        <div className="gradient-container mb-16" id="container">
          <div className="gradient-orbs-light">
            <div className="third-orb"></div>
            <div className="fourth-line"></div>
          </div>

          <div className="gradient-orbs-dark">
            <div className="third-orb"></div>
            <div className="fourth-line"></div>
          </div>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
